name: Generate Dataset
on: 
  push:
    branches:
      - main
    paths:
      - image-to.npz-py
      - images/*

jobs:
  generate-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas cv2 random

      - name: Run Image To NPZ Script
        run: python image-to-npz.py 
      
      - name: Commit Changes
        run: |
          git config --global user.email 'jec.castanos@gmail.com'
          git config --global user.name 'jscastanos'
          git add .
          git commit -m "chore[BOT]: generate dataset"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true 